### PR TITLE
Fix authentication

### PR DESCRIPTION
**Pull request by bigkraig**
Based on https://github.com/CJNE/pyporscheconnectapi/commit/c3de2043dbfa4c562ee5ad18ac9feef4a592e646

### CODE REVIEW

**Comment by martijndierckx** [comment]
Thx for the PR.
I do see a mix of changes:
- Code optimisations/changes
- Bugfixes
- Example scripts (not to be included)
- ...?

Could you split those changes in multiple PRs?
Have you tested the changes and are they confirmed to work?

thx
M

**Comment by bigkraig** [comment]
Well, the authentication piece was fixed and I started to patch a bug where not all cars support the features requested in getVehicle, but I ran into another problem where the car capabilities are not consisitently returned from the API unless you log in via the app, which makes it unreliable for what I wanted in homebridge.

**Comment by jasper-seinhorst** [comment]
@bigkraig I tested your changes, but it seems it breaks the capabilities as you mentioned. Is there a work around, or is it a breaking change on Porsches side?

**Comment by bigkraig** [comment]
> @bigkraig I tested your changes, but it seems it breaks the capabilities as you mentioned. Is there a work around, or is it a breaking change on Porsches side?

I read on a PR or issue for the python package that people were having the capabilities problem and resolving it by logging into the account with an app (or maybe the website) and at least for a while, the api would start to work again.

 -- it's been a while and maybe i am misremembering, I was looking at PR https://github.com/CJNE/pyporscheconnectapi/issues/37 which looked like what I remember, but that appears to be a purely auth problem and not a missing capabilities. one of my cars is a GT3 and it does not have all of the same API responses that are fetched as part of the `getVehicles` function, which was causing problems with the homebridge plugin.

**Comment by bigkraig** [comment]
see https://github.com/CJNE/pyporscheconnectapi/issues/37

**Comment by bigkraig** [comment]
ok @martijndierckx, i've cleaned this up and fixed the auth scopes, which was the source of some of my problems. this is now working for me in homebridge

```
[1/26/2024, 7:16:25 PM] [homebridge-porsche-taycan] Loaded homebridge-porsche-taycan v0.14.0 child bridge successfully
[1/26/2024, 7:16:25 PM] Loaded 0 cached accessories from cachedAccessories.0E9573A8F96B.
[1/26/2024, 7:16:25 PM] [homebridge-porsche-taycan] Authentication
[1/26/2024, 7:16:25 PM] [homebridge-porsche-taycan] Retrieving available vehicles
[1/26/2024, 7:16:25 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-porsche-taycan) is running on port 58977.
[1/26/2024, 7:16:36 PM] [homebridge-porsche-taycan] Your Porsche 911 GT3 is not supported, it has an unsupported engine type UNKNOWN
[1/26/2024, 7:16:36 PM] [homebridge-porsche-taycan] Charger added as accessory
[1/26/2024, 7:16:36 PM] [homebridge-porsche-taycan] Direct Climatisation added as accessory
[1/26/2024, 7:16:36 PM] [homebridge-porsche-taycan] Updating vehicle data for Taycan Turbo S Cross Turismo
[1/26/2024, 7:16:39 PM] [homebridge-porsche-taycan] Battery level -> 77
```

**Comment by jasper-seinhorst** [comment]
@bigkraig I tested your code. For me Porsche Connect authentication is fixed. But the getVehicles promise returns an empty array. I did some debugging and also the result of Porsche Connect api returns no data. 

my.porsche.com works, so I don't think this is an outage at their side. Can you confirm?

**Comment by bigkraig** [comment]
still working:

```
[2/1/2024, 9:07:21 AM] [homebridge-porsche-taycan] Your Porsche 911 GT3 is not supported, it has an unsupported engine type UNKNOWN
[2/1/2024, 9:07:21 AM] [homebridge-porsche-taycan] Updating vehicle data for Taycan Turbo S Cross Turismo
[2/1/2024, 9:07:24 AM] [homebridge-porsche-taycan] Battery level -> 84
```

**Comment by martijndierckx** [comment]
tested, and seems to work.
Will release new version

**Pull request merged**
